//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18408 版自动生成。
// 
#pragma warning disable 1591

namespace IAM.WebReferenceSapUserInfo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“Policy”。
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZIAM_READ_SAP_USER_INFOMATION_SOAP12", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZIAM_READ_SAP_USER_INFOMATIONService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZiamReadSapUserInfomationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZIAM_READ_SAP_USER_INFOMATIONService() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::IAM.Properties.Settings.Default.IAM_WebReferenceSapUserInfo_ZIAM_READ_SAP_USER_INFOMATIONService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZiamReadSapUserInfomationCompletedEventHandler ZiamReadSapUserInfomationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZiamReadSapUserInfomationResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZiamReadSapUserInfomationResponse ZiamReadSapUserInfomation([System.Xml.Serialization.XmlElementAttribute("ZiamReadSapUserInfomation", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZiamReadSapUserInfomation ZiamReadSapUserInfomation1) {
            object[] results = this.Invoke("ZiamReadSapUserInfomation", new object[] {
                        ZiamReadSapUserInfomation1});
            return ((ZiamReadSapUserInfomationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZiamReadSapUserInfomationAsync(ZiamReadSapUserInfomation ZiamReadSapUserInfomation1) {
            this.ZiamReadSapUserInfomationAsync(ZiamReadSapUserInfomation1, null);
        }
        
        /// <remarks/>
        public void ZiamReadSapUserInfomationAsync(ZiamReadSapUserInfomation ZiamReadSapUserInfomation1, object userState) {
            if ((this.ZiamReadSapUserInfomationOperationCompleted == null)) {
                this.ZiamReadSapUserInfomationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZiamReadSapUserInfomationOperationCompleted);
            }
            this.InvokeAsync("ZiamReadSapUserInfomation", new object[] {
                        ZiamReadSapUserInfomation1}, this.ZiamReadSapUserInfomationOperationCompleted, userState);
        }
        
        private void OnZiamReadSapUserInfomationOperationCompleted(object arg) {
            if ((this.ZiamReadSapUserInfomationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZiamReadSapUserInfomationCompleted(this, new ZiamReadSapUserInfomationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZiamReadSapUserInfomation {
        
        private string cacheResultsField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string CacheResults {
            get {
                return this.cacheResultsField;
            }
            set {
                this.cacheResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiuclass {
        
        private string licTypeField;
        
        private string specVersField;
        
        private decimal countrySurchargeField;
        
        private string substituteFromField;
        
        private string substituteUntilField;
        
        private string sysidField;
        
        private string clientField;
        
        private string bnameChargeableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string LicType {
            get {
                return this.licTypeField;
            }
            set {
                this.licTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string SpecVers {
            get {
                return this.specVersField;
            }
            set {
                this.specVersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public decimal CountrySurcharge {
            get {
                return this.countrySurchargeField;
            }
            set {
                this.countrySurchargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string SubstituteFrom {
            get {
                return this.substituteFromField;
            }
            set {
                this.substituteFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string SubstituteUntil {
            get {
                return this.substituteUntilField;
            }
            set {
                this.substituteUntilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Sysid {
            get {
                return this.sysidField;
            }
            set {
                this.sysidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string BnameChargeable {
            get {
                return this.bnameChargeableField;
            }
            set {
                this.bnameChargeableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiret2 {
        
        private string typeField;
        
        private string idField;
        
        private string numberField;
        
        private string messageField;
        
        private string logNoField;
        
        private string logMsgNoField;
        
        private string messageV1Field;
        
        private string messageV2Field;
        
        private string messageV3Field;
        
        private string messageV4Field;
        
        private string parameterField;
        
        private int rowField;
        
        private string fieldField;
        
        private string systemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = (System.Xml.Schema.XmlSchemaForm)2)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string LogNo {
            get {
                return this.logNoField;
            }
            set {
                this.logNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string LogMsgNo {
            get {
                return this.logMsgNoField;
            }
            set {
                this.logMsgNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string MessageV1 {
            get {
                return this.messageV1Field;
            }
            set {
                this.messageV1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string MessageV2 {
            get {
                return this.messageV2Field;
            }
            set {
                this.messageV2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string MessageV3 {
            get {
                return this.messageV3Field;
            }
            set {
                this.messageV3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string MessageV4 {
            get {
                return this.messageV4Field;
            }
            set {
                this.messageV4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public int Row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string System {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiprof {
        
        private string bapiprof1Field;
        
        private string bapiptextField;
        
        private string bapitypeField;
        
        private string bapiaktpsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Bapiprof", Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Bapiprof1 {
            get {
                return this.bapiprof1Field;
            }
            set {
                this.bapiprof1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Bapiptext {
            get {
                return this.bapiptextField;
            }
            set {
                this.bapiptextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Bapitype {
            get {
                return this.bapitypeField;
            }
            set {
                this.bapitypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Bapiaktps {
            get {
                return this.bapiaktpsField;
            }
            set {
                this.bapiaktpsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiparam {
        
        private string paridField;
        
        private string parvaField;
        
        private string partxtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Parid {
            get {
                return this.paridField;
            }
            set {
                this.paridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Parva {
            get {
                return this.parvaField;
            }
            set {
                this.parvaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Partxt {
            get {
                return this.partxtField;
            }
            set {
                this.partxtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapilogond {
        
        private string gltgvField;
        
        private string gltgbField;
        
        private string ustypField;
        
        private string classField;
        
        private string accntField;
        
        private string tzoneField;
        
        private string ltimeField;
        
        private byte[] bcodeField;
        
        private string codvnField;
        
        private byte[] passcodeField;
        
        private string codvcField;
        
        private string pwdsaltedhashField;
        
        private string codvsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Gltgv {
            get {
                return this.gltgvField;
            }
            set {
                this.gltgvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Gltgb {
            get {
                return this.gltgbField;
            }
            set {
                this.gltgbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Ustyp {
            get {
                return this.ustypField;
            }
            set {
                this.ustypField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Accnt {
            get {
                return this.accntField;
            }
            set {
                this.accntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Tzone {
            get {
                return this.tzoneField;
            }
            set {
                this.tzoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Ltime {
            get {
                return this.ltimeField;
            }
            set {
                this.ltimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2, DataType="base64Binary")]
        public byte[] Bcode {
            get {
                return this.bcodeField;
            }
            set {
                this.bcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Codvn {
            get {
                return this.codvnField;
            }
            set {
                this.codvnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2, DataType="base64Binary")]
        public byte[] Passcode {
            get {
                return this.passcodeField;
            }
            set {
                this.passcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Codvc {
            get {
                return this.codvcField;
            }
            set {
                this.codvcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Pwdsaltedhash {
            get {
                return this.pwdsaltedhashField;
            }
            set {
                this.pwdsaltedhashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Codvs {
            get {
                return this.codvsField;
            }
            set {
                this.codvsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapimoddat {
        
        private string moddateField;
        
        private string modtimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Moddate {
            get {
                return this.moddateField;
            }
            set {
                this.moddateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Modtime {
            get {
                return this.modtimeField;
            }
            set {
                this.modtimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapislockd {
        
        private string wrngLogonField;
        
        private string localLockField;
        
        private string globLockField;
        
        private string noUserPwField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string WrngLogon {
            get {
                return this.wrngLogonField;
            }
            set {
                this.wrngLogonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string LocalLock {
            get {
                return this.localLockField;
            }
            set {
                this.localLockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string GlobLock {
            get {
                return this.globLockField;
            }
            set {
                this.globLockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string NoUserPw {
            get {
                return this.noUserPwField;
            }
            set {
                this.noUserPwField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapidefaul {
        
        private string stcodField;
        
        private string spldField;
        
        private string splgField;
        
        private string spdbField;
        
        private string spdaField;
        
        private string datfmField;
        
        private string dcpfmField;
        
        private string languField;
        
        private string cattkennzField;
        
        private string kostlField;
        
        private string startMenuField;
        
        private string timefmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Stcod {
            get {
                return this.stcodField;
            }
            set {
                this.stcodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Spld {
            get {
                return this.spldField;
            }
            set {
                this.spldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Splg {
            get {
                return this.splgField;
            }
            set {
                this.splgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Spdb {
            get {
                return this.spdbField;
            }
            set {
                this.spdbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Spda {
            get {
                return this.spdaField;
            }
            set {
                this.spdaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Datfm {
            get {
                return this.datfmField;
            }
            set {
                this.datfmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Dcpfm {
            get {
                return this.dcpfmField;
            }
            set {
                this.dcpfmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Langu {
            get {
                return this.languField;
            }
            set {
                this.languField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Cattkennz {
            get {
                return this.cattkennzField;
            }
            set {
                this.cattkennzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Kostl {
            get {
                return this.kostlField;
            }
            set {
                this.kostlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string StartMenu {
            get {
                return this.startMenuField;
            }
            set {
                this.startMenuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Timefm {
            get {
                return this.timefmField;
            }
            set {
                this.timefmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiadtel {
        
        private string countryField;
        
        private string countryisoField;
        
        private string stdNoField;
        
        private string telephoneField;
        
        private string extensionField;
        
        private string telNoField;
        
        private string callerNoField;
        
        private string stdRecipField;
        
        private string r3UserField;
        
        private string homeFlagField;
        
        private string consnumberField;
        
        private string errorflagField;
        
        private string flgNouseField;
        
        private string validFromField;
        
        private string validToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Countryiso {
            get {
                return this.countryisoField;
            }
            set {
                this.countryisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string StdNo {
            get {
                return this.stdNoField;
            }
            set {
                this.stdNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string TelNo {
            get {
                return this.telNoField;
            }
            set {
                this.telNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string CallerNo {
            get {
                return this.callerNoField;
            }
            set {
                this.callerNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string StdRecip {
            get {
                return this.stdRecipField;
            }
            set {
                this.stdRecipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string R3User {
            get {
                return this.r3UserField;
            }
            set {
                this.r3UserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string HomeFlag {
            get {
                return this.homeFlagField;
            }
            set {
                this.homeFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Consnumber {
            get {
                return this.consnumberField;
            }
            set {
                this.consnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Errorflag {
            get {
                return this.errorflagField;
            }
            set {
                this.errorflagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string FlgNouse {
            get {
                return this.flgNouseField;
            }
            set {
                this.flgNouseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string ValidTo {
            get {
                return this.validToField;
            }
            set {
                this.validToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiadsmtp {
        
        private string stdNoField;
        
        private string eMailField;
        
        private string emailSrchField;
        
        private string stdRecipField;
        
        private string r3UserField;
        
        private string encodeField;
        
        private string tnefField;
        
        private string homeFlagField;
        
        private string consnumberField;
        
        private string errorflagField;
        
        private string flgNouseField;
        
        private string validFromField;
        
        private string validToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string StdNo {
            get {
                return this.stdNoField;
            }
            set {
                this.stdNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string EmailSrch {
            get {
                return this.emailSrchField;
            }
            set {
                this.emailSrchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string StdRecip {
            get {
                return this.stdRecipField;
            }
            set {
                this.stdRecipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string R3User {
            get {
                return this.r3UserField;
            }
            set {
                this.r3UserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Encode {
            get {
                return this.encodeField;
            }
            set {
                this.encodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Tnef {
            get {
                return this.tnefField;
            }
            set {
                this.tnefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string HomeFlag {
            get {
                return this.homeFlagField;
            }
            set {
                this.homeFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Consnumber {
            get {
                return this.consnumberField;
            }
            set {
                this.consnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Errorflag {
            get {
                return this.errorflagField;
            }
            set {
                this.errorflagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string FlgNouse {
            get {
                return this.flgNouseField;
            }
            set {
                this.flgNouseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string ValidTo {
            get {
                return this.validToField;
            }
            set {
                this.validToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiaddr3 {
        
        private string persNoField;
        
        private string addrNoField;
        
        private string titlePField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string birthNameField;
        
        private string middlenameField;
        
        private string secondnameField;
        
        private string fullnameField;
        
        private string fullnameXField;
        
        private string titleAca1Field;
        
        private string titleAca2Field;
        
        private string prefix1Field;
        
        private string prefix2Field;
        
        private string titleSpplField;
        
        private string nicknameField;
        
        private string initialsField;
        
        private string nameformatField;
        
        private string namcountryField;
        
        private string languPField;
        
        private string langupIsoField;
        
        private string sort1PField;
        
        private string sort2PField;
        
        private string departmentField;
        
        private string functionField;
        
        private string buildingPField;
        
        private string floorPField;
        
        private string roomNoPField;
        
        private string initsSigField;
        
        private string inhouseMlField;
        
        private string commTypeField;
        
        private string titleField;
        
        private string nameField;
        
        private string name2Field;
        
        private string name3Field;
        
        private string name4Field;
        
        private string cONameField;
        
        private string cityField;
        
        private string districtField;
        
        private string cityNoField;
        
        private string distrctNoField;
        
        private string chckstatusField;
        
        private string postlCod1Field;
        
        private string postlCod2Field;
        
        private string postlCod3Field;
        
        private string poBoxField;
        
        private string poBoxCitField;
        
        private string pboxcitNoField;
        
        private string delivDisField;
        
        private string transpzoneField;
        
        private string streetField;
        
        private string streetNoField;
        
        private string strAbbrField;
        
        private string houseNoField;
        
        private string houseNo2Field;
        
        private string strSuppl1Field;
        
        private string strSuppl2Field;
        
        private string strSuppl3Field;
        
        private string locationField;
        
        private string buildingField;
        
        private string floorField;
        
        private string roomNoField;
        
        private string countryField;
        
        private string countryisoField;
        
        private string languField;
        
        private string languIsoField;
        
        private string regionField;
        
        private string sort1Field;
        
        private string sort2Field;
        
        private string timeZoneField;
        
        private string taxjurcodeField;
        
        private string adrNotesField;
        
        private string tel1NumbrField;
        
        private string tel1ExtField;
        
        private string faxNumberField;
        
        private string faxExtensField;
        
        private string eMailField;
        
        private string buildLongField;
        
        private string regiogroupField;
        
        private string homeCityField;
        
        private string homecitynoField;
        
        private string pcode1ExtField;
        
        private string pcode2ExtField;
        
        private string pcode3ExtField;
        
        private string poWONoField;
        
        private string poBoxRegField;
        
        private string poboxCtryField;
        
        private string poCtryisoField;
        
        private string dontUseSField;
        
        private string dontUsePField;
        
        private string houseNo3Field;
        
        private string languCrPField;
        
        private string langucpisoField;
        
        private string poBoxLobbyField;
        
        private string deliServTypeField;
        
        private string deliServNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string PersNo {
            get {
                return this.persNoField;
            }
            set {
                this.persNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string AddrNo {
            get {
                return this.addrNoField;
            }
            set {
                this.addrNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string TitleP {
            get {
                return this.titlePField;
            }
            set {
                this.titlePField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string BirthName {
            get {
                return this.birthNameField;
            }
            set {
                this.birthNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Middlename {
            get {
                return this.middlenameField;
            }
            set {
                this.middlenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Secondname {
            get {
                return this.secondnameField;
            }
            set {
                this.secondnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string FullnameX {
            get {
                return this.fullnameXField;
            }
            set {
                this.fullnameXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string TitleAca1 {
            get {
                return this.titleAca1Field;
            }
            set {
                this.titleAca1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string TitleAca2 {
            get {
                return this.titleAca2Field;
            }
            set {
                this.titleAca2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Prefix1 {
            get {
                return this.prefix1Field;
            }
            set {
                this.prefix1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Prefix2 {
            get {
                return this.prefix2Field;
            }
            set {
                this.prefix2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string TitleSppl {
            get {
                return this.titleSpplField;
            }
            set {
                this.titleSpplField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Nickname {
            get {
                return this.nicknameField;
            }
            set {
                this.nicknameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Nameformat {
            get {
                return this.nameformatField;
            }
            set {
                this.nameformatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Namcountry {
            get {
                return this.namcountryField;
            }
            set {
                this.namcountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string LanguP {
            get {
                return this.languPField;
            }
            set {
                this.languPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string LangupIso {
            get {
                return this.langupIsoField;
            }
            set {
                this.langupIsoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Sort1P {
            get {
                return this.sort1PField;
            }
            set {
                this.sort1PField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Sort2P {
            get {
                return this.sort2PField;
            }
            set {
                this.sort2PField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string BuildingP {
            get {
                return this.buildingPField;
            }
            set {
                this.buildingPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string FloorP {
            get {
                return this.floorPField;
            }
            set {
                this.floorPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string RoomNoP {
            get {
                return this.roomNoPField;
            }
            set {
                this.roomNoPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string InitsSig {
            get {
                return this.initsSigField;
            }
            set {
                this.initsSigField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string InhouseMl {
            get {
                return this.inhouseMlField;
            }
            set {
                this.inhouseMlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string CommType {
            get {
                return this.commTypeField;
            }
            set {
                this.commTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Name2 {
            get {
                return this.name2Field;
            }
            set {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Name3 {
            get {
                return this.name3Field;
            }
            set {
                this.name3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Name4 {
            get {
                return this.name4Field;
            }
            set {
                this.name4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string COName {
            get {
                return this.cONameField;
            }
            set {
                this.cONameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string CityNo {
            get {
                return this.cityNoField;
            }
            set {
                this.cityNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string DistrctNo {
            get {
                return this.distrctNoField;
            }
            set {
                this.distrctNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Chckstatus {
            get {
                return this.chckstatusField;
            }
            set {
                this.chckstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string PostlCod1 {
            get {
                return this.postlCod1Field;
            }
            set {
                this.postlCod1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string PostlCod2 {
            get {
                return this.postlCod2Field;
            }
            set {
                this.postlCod2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string PostlCod3 {
            get {
                return this.postlCod3Field;
            }
            set {
                this.postlCod3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string PoBox {
            get {
                return this.poBoxField;
            }
            set {
                this.poBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string PoBoxCit {
            get {
                return this.poBoxCitField;
            }
            set {
                this.poBoxCitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string PboxcitNo {
            get {
                return this.pboxcitNoField;
            }
            set {
                this.pboxcitNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string DelivDis {
            get {
                return this.delivDisField;
            }
            set {
                this.delivDisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Transpzone {
            get {
                return this.transpzoneField;
            }
            set {
                this.transpzoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string StreetNo {
            get {
                return this.streetNoField;
            }
            set {
                this.streetNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string StrAbbr {
            get {
                return this.strAbbrField;
            }
            set {
                this.strAbbrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string HouseNo {
            get {
                return this.houseNoField;
            }
            set {
                this.houseNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string HouseNo2 {
            get {
                return this.houseNo2Field;
            }
            set {
                this.houseNo2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string StrSuppl1 {
            get {
                return this.strSuppl1Field;
            }
            set {
                this.strSuppl1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string StrSuppl2 {
            get {
                return this.strSuppl2Field;
            }
            set {
                this.strSuppl2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string StrSuppl3 {
            get {
                return this.strSuppl3Field;
            }
            set {
                this.strSuppl3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string RoomNo {
            get {
                return this.roomNoField;
            }
            set {
                this.roomNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Countryiso {
            get {
                return this.countryisoField;
            }
            set {
                this.countryisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Langu {
            get {
                return this.languField;
            }
            set {
                this.languField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string LanguIso {
            get {
                return this.languIsoField;
            }
            set {
                this.languIsoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Sort1 {
            get {
                return this.sort1Field;
            }
            set {
                this.sort1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Sort2 {
            get {
                return this.sort2Field;
            }
            set {
                this.sort2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string TimeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Taxjurcode {
            get {
                return this.taxjurcodeField;
            }
            set {
                this.taxjurcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string AdrNotes {
            get {
                return this.adrNotesField;
            }
            set {
                this.adrNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Tel1Numbr {
            get {
                return this.tel1NumbrField;
            }
            set {
                this.tel1NumbrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Tel1Ext {
            get {
                return this.tel1ExtField;
            }
            set {
                this.tel1ExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string FaxExtens {
            get {
                return this.faxExtensField;
            }
            set {
                this.faxExtensField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string BuildLong {
            get {
                return this.buildLongField;
            }
            set {
                this.buildLongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Regiogroup {
            get {
                return this.regiogroupField;
            }
            set {
                this.regiogroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string HomeCity {
            get {
                return this.homeCityField;
            }
            set {
                this.homeCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Homecityno {
            get {
                return this.homecitynoField;
            }
            set {
                this.homecitynoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Pcode1Ext {
            get {
                return this.pcode1ExtField;
            }
            set {
                this.pcode1ExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Pcode2Ext {
            get {
                return this.pcode2ExtField;
            }
            set {
                this.pcode2ExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Pcode3Ext {
            get {
                return this.pcode3ExtField;
            }
            set {
                this.pcode3ExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string PoWONo {
            get {
                return this.poWONoField;
            }
            set {
                this.poWONoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string PoBoxReg {
            get {
                return this.poBoxRegField;
            }
            set {
                this.poBoxRegField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string PoboxCtry {
            get {
                return this.poboxCtryField;
            }
            set {
                this.poboxCtryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string PoCtryiso {
            get {
                return this.poCtryisoField;
            }
            set {
                this.poCtryisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string DontUseS {
            get {
                return this.dontUseSField;
            }
            set {
                this.dontUseSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string DontUseP {
            get {
                return this.dontUsePField;
            }
            set {
                this.dontUsePField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string HouseNo3 {
            get {
                return this.houseNo3Field;
            }
            set {
                this.houseNo3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string LanguCrP {
            get {
                return this.languCrPField;
            }
            set {
                this.languCrPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Langucpiso {
            get {
                return this.langucpisoField;
            }
            set {
                this.langucpisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string PoBoxLobby {
            get {
                return this.poBoxLobbyField;
            }
            set {
                this.poBoxLobbyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string DeliServType {
            get {
                return this.deliServTypeField;
            }
            set {
                this.deliServTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string DeliServNumber {
            get {
                return this.deliServNumberField;
            }
            set {
                this.deliServNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiagr {
        
        private string agrNameField;
        
        private string fromDatField;
        
        private string toDatField;
        
        private string agrTextField;
        
        private string orgFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string AgrName {
            get {
                return this.agrNameField;
            }
            set {
                this.agrNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string FromDat {
            get {
                return this.fromDatField;
            }
            set {
                this.fromDatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string ToDat {
            get {
                return this.toDatField;
            }
            set {
                this.toDatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string AgrText {
            get {
                return this.agrTextField;
            }
            set {
                this.agrTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string OrgFlag {
            get {
                return this.orgFlagField;
            }
            set {
                this.orgFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZiamReadSapUserInfomationResponse {
        
        private Bapiagr[] activitygroupsEtField;
        
        private Bapiaddr3 addressField;
        
        private Bapiadsmtp[] addsmtpEtField;
        
        private Bapiadtel[] addtelEtField;
        
        private Bapidefaul defaultsField;
        
        private Bapislockd islockedField;
        
        private Bapimoddat lastmodifiedField;
        
        private Bapilogond logondataField;
        
        private Bapiparam[] parameterEtField;
        
        private Bapiprof[] profilesEtField;
        
        private Bapiret2[] returnEtField;
        
        private Bapiuclass uclassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=(System.Xml.Schema.XmlSchemaForm)2, IsNullable=false)]
        public Bapiagr[] ActivitygroupsEt {
            get {
                return this.activitygroupsEtField;
            }
            set {
                this.activitygroupsEtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public Bapiaddr3 Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=(System.Xml.Schema.XmlSchemaForm)2, IsNullable=false)]
        public Bapiadsmtp[] AddsmtpEt {
            get {
                return this.addsmtpEtField;
            }
            set {
                this.addsmtpEtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=(System.Xml.Schema.XmlSchemaForm)2, IsNullable=false)]
        public Bapiadtel[] AddtelEt {
            get {
                return this.addtelEtField;
            }
            set {
                this.addtelEtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public Bapidefaul Defaults {
            get {
                return this.defaultsField;
            }
            set {
                this.defaultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public Bapislockd Islocked {
            get {
                return this.islockedField;
            }
            set {
                this.islockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public Bapimoddat Lastmodified {
            get {
                return this.lastmodifiedField;
            }
            set {
                this.lastmodifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public Bapilogond Logondata {
            get {
                return this.logondataField;
            }
            set {
                this.logondataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=(System.Xml.Schema.XmlSchemaForm)2, IsNullable=false)]
        public Bapiparam[] ParameterEt {
            get {
                return this.parameterEtField;
            }
            set {
                this.parameterEtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=(System.Xml.Schema.XmlSchemaForm)2, IsNullable=false)]
        public Bapiprof[] ProfilesEt {
            get {
                return this.profilesEtField;
            }
            set {
                this.profilesEtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=(System.Xml.Schema.XmlSchemaForm)2, IsNullable=false)]
        public Bapiret2[] ReturnEt {
            get {
                return this.returnEtField;
            }
            set {
                this.returnEtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public Bapiuclass Uclass {
            get {
                return this.uclassField;
            }
            set {
                this.uclassField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ZiamReadSapUserInfomationCompletedEventHandler(object sender, ZiamReadSapUserInfomationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZiamReadSapUserInfomationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZiamReadSapUserInfomationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZiamReadSapUserInfomationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZiamReadSapUserInfomationResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591