//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18449 版自动生成。
// 
#pragma warning disable 1591

namespace IAM.WebReference3 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://shac.com.cn/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QueryAllUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryAllWorkGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryUserWorkGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryAllComputerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::IAM.Properties.Settings.Default.IAM_WebReference3_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QueryAllUserCompletedEventHandler QueryAllUserCompleted;
        
        /// <remarks/>
        public event QueryAllWorkGroupCompletedEventHandler QueryAllWorkGroupCompleted;
        
        /// <remarks/>
        public event QueryUserWorkGroupCompletedEventHandler QueryUserWorkGroupCompleted;
        
        /// <remarks/>
        public event QueryAllComputerCompletedEventHandler QueryAllComputerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shac.com.cn/QueryAllUser", RequestNamespace="http://shac.com.cn/", ResponseNamespace="http://shac.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserResultInfo[] QueryAllUser() {
            object[] results = this.Invoke("QueryAllUser", new object[0]);
            return ((UserResultInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryAllUserAsync() {
            this.QueryAllUserAsync(null);
        }
        
        /// <remarks/>
        public void QueryAllUserAsync(object userState) {
            if ((this.QueryAllUserOperationCompleted == null)) {
                this.QueryAllUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryAllUserOperationCompleted);
            }
            this.InvokeAsync("QueryAllUser", new object[0], this.QueryAllUserOperationCompleted, userState);
        }
        
        private void OnQueryAllUserOperationCompleted(object arg) {
            if ((this.QueryAllUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryAllUserCompleted(this, new QueryAllUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shac.com.cn/QueryAllWorkGroup", RequestNamespace="http://shac.com.cn/", ResponseNamespace="http://shac.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GroupResultInfo[] QueryAllWorkGroup() {
            object[] results = this.Invoke("QueryAllWorkGroup", new object[0]);
            return ((GroupResultInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryAllWorkGroupAsync() {
            this.QueryAllWorkGroupAsync(null);
        }
        
        /// <remarks/>
        public void QueryAllWorkGroupAsync(object userState) {
            if ((this.QueryAllWorkGroupOperationCompleted == null)) {
                this.QueryAllWorkGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryAllWorkGroupOperationCompleted);
            }
            this.InvokeAsync("QueryAllWorkGroup", new object[0], this.QueryAllWorkGroupOperationCompleted, userState);
        }
        
        private void OnQueryAllWorkGroupOperationCompleted(object arg) {
            if ((this.QueryAllWorkGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryAllWorkGroupCompleted(this, new QueryAllWorkGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shac.com.cn/QueryUserWorkGroup", RequestNamespace="http://shac.com.cn/", ResponseNamespace="http://shac.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GroupResultInfo[] QueryUserWorkGroup(string Uid) {
            object[] results = this.Invoke("QueryUserWorkGroup", new object[] {
                        Uid});
            return ((GroupResultInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryUserWorkGroupAsync(string Uid) {
            this.QueryUserWorkGroupAsync(Uid, null);
        }
        
        /// <remarks/>
        public void QueryUserWorkGroupAsync(string Uid, object userState) {
            if ((this.QueryUserWorkGroupOperationCompleted == null)) {
                this.QueryUserWorkGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryUserWorkGroupOperationCompleted);
            }
            this.InvokeAsync("QueryUserWorkGroup", new object[] {
                        Uid}, this.QueryUserWorkGroupOperationCompleted, userState);
        }
        
        private void OnQueryUserWorkGroupOperationCompleted(object arg) {
            if ((this.QueryUserWorkGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryUserWorkGroupCompleted(this, new QueryUserWorkGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shac.com.cn/QueryAllComputer", RequestNamespace="http://shac.com.cn/", ResponseNamespace="http://shac.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ComputerResultInfo[] QueryAllComputer() {
            object[] results = this.Invoke("QueryAllComputer", new object[0]);
            return ((ComputerResultInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryAllComputerAsync() {
            this.QueryAllComputerAsync(null);
        }
        
        /// <remarks/>
        public void QueryAllComputerAsync(object userState) {
            if ((this.QueryAllComputerOperationCompleted == null)) {
                this.QueryAllComputerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryAllComputerOperationCompleted);
            }
            this.InvokeAsync("QueryAllComputer", new object[0], this.QueryAllComputerOperationCompleted, userState);
        }
        
        private void OnQueryAllComputerOperationCompleted(object arg) {
            if ((this.QueryAllComputerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryAllComputerCompleted(this, new QueryAllComputerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://shac.com.cn/")]
    public partial class UserResultInfo {
        
        private string accountnameField;
        
        private string idField;
        
        private string cnField;
        
        private string displaynameField;
        
        private string descriptionField;
        
        private string departmentField;
        
        private int mDBOverHardQuotaLimitField;
        
        private int mDBOverQuotaLimitField;
        
        private int mDBStorageQuotaField;
        
        private string jobField;
        
        private string groupField;
        
        private string mobileField;
        
        private string telField;
        
        private string emailField;
        
        private string lyncField;
        
        private bool enabledField;
        
        private string[] workGroupsField;
        
        private System.DateTime pwdLastSetTimeField;
        
        private System.DateTime lastLoginTimeField;
        
        private string homeMDBField;
        
        private string accountExpiresField;
        
        private string homeDirectoryField;
        
        private string homeDriveField;
        
        private string homeMTAField;
        
        /// <remarks/>
        public string Accountname {
            get {
                return this.accountnameField;
            }
            set {
                this.accountnameField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Cn {
            get {
                return this.cnField;
            }
            set {
                this.cnField = value;
            }
        }
        
        /// <remarks/>
        public string Displayname {
            get {
                return this.displaynameField;
            }
            set {
                this.displaynameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public int mDBOverHardQuotaLimit {
            get {
                return this.mDBOverHardQuotaLimitField;
            }
            set {
                this.mDBOverHardQuotaLimitField = value;
            }
        }
        
        /// <remarks/>
        public int mDBOverQuotaLimit {
            get {
                return this.mDBOverQuotaLimitField;
            }
            set {
                this.mDBOverQuotaLimitField = value;
            }
        }
        
        /// <remarks/>
        public int mDBStorageQuota {
            get {
                return this.mDBStorageQuotaField;
            }
            set {
                this.mDBStorageQuotaField = value;
            }
        }
        
        /// <remarks/>
        public string Job {
            get {
                return this.jobField;
            }
            set {
                this.jobField = value;
            }
        }
        
        /// <remarks/>
        public string Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Lync {
            get {
                return this.lyncField;
            }
            set {
                this.lyncField = value;
            }
        }
        
        /// <remarks/>
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        public string[] WorkGroups {
            get {
                return this.workGroupsField;
            }
            set {
                this.workGroupsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime pwdLastSetTime {
            get {
                return this.pwdLastSetTimeField;
            }
            set {
                this.pwdLastSetTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastLoginTime {
            get {
                return this.lastLoginTimeField;
            }
            set {
                this.lastLoginTimeField = value;
            }
        }
        
        /// <remarks/>
        public string HomeMDB {
            get {
                return this.homeMDBField;
            }
            set {
                this.homeMDBField = value;
            }
        }
        
        /// <remarks/>
        public string AccountExpires {
            get {
                return this.accountExpiresField;
            }
            set {
                this.accountExpiresField = value;
            }
        }
        
        /// <remarks/>
        public string HomeDirectory {
            get {
                return this.homeDirectoryField;
            }
            set {
                this.homeDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string HomeDrive {
            get {
                return this.homeDriveField;
            }
            set {
                this.homeDriveField = value;
            }
        }
        
        /// <remarks/>
        public string HomeMTA {
            get {
                return this.homeMTAField;
            }
            set {
                this.homeMTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://shac.com.cn/")]
    public partial class ComputerResultInfo {
        
        private string nameField;
        
        private string descriptionField;
        
        private string expiryDateField;
        
        private bool enabledField;
        
        private string[] workGroupsField;
        
        private System.DateTime lastLoginTimeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        public string[] WorkGroups {
            get {
                return this.workGroupsField;
            }
            set {
                this.workGroupsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastLoginTime {
            get {
                return this.lastLoginTimeField;
            }
            set {
                this.lastLoginTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://shac.com.cn/")]
    public partial class GroupResultInfo {
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void QueryAllUserCompletedEventHandler(object sender, QueryAllUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryAllUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryAllUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserResultInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserResultInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void QueryAllWorkGroupCompletedEventHandler(object sender, QueryAllWorkGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryAllWorkGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryAllWorkGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GroupResultInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GroupResultInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void QueryUserWorkGroupCompletedEventHandler(object sender, QueryUserWorkGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryUserWorkGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryUserWorkGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GroupResultInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GroupResultInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void QueryAllComputerCompletedEventHandler(object sender, QueryAllComputerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryAllComputerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryAllComputerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ComputerResultInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ComputerResultInfo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591