//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.124.88.176:8383/hecprod/modules/sys/WS/role/cux_role_ws_query.svc")]
        public string IAM_WebReference_auto_service {
            get {
                return ((string)(this["IAM_WebReference_auto_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.124.88.176:8383/hecprod/modules/sys/WS/company/cux_company_ws_query.svc" +
            "")]
        public string IAM_WebReference1_auto_service {
            get {
                return ((string)(this["IAM_WebReference1_auto_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.124.88.176:8383/hecprod/modules/sys/WS/user/cux_user_ws_query.svc")]
        public string IAM_WebReference2_auto_service {
            get {
                return ((string)(this["IAM_WebReference2_auto_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.124.88.229:8000/sap/bc/srt/rfc/sap/ziam_get_sap_user_list/800/ziam_get_" +
            "sap_user_list/ziam_get_sap_user_list")]
        public string IAM_WebReferenceSapUserList_ZIAM_GET_SAP_USER_LISTService {
            get {
                return ((string)(this["IAM_WebReferenceSapUserList_ZIAM_GET_SAP_USER_LISTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.124.88.229:8000/sap/bc/srt/rfc/sap/ziam_get_roles_list/800/ziam_get_rol" +
            "es_list/ziam_get_roles_list")]
        public string IAM_WebReferenceSapRoleList_ZIAM_GET_ROLES_LISTService {
            get {
                return ((string)(this["IAM_WebReferenceSapRoleList_ZIAM_GET_ROLES_LISTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.124.88.149:8989/axis2/services/MyWESService.MyWESServiceHttpSoap11Endpo" +
            "int")]
        public string IAM_WebReferenceTC_MyWESService {
            get {
                return ((string)(this["IAM_WebReferenceTC_MyWESService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.124.88.149:8989/axis2/services/MyTCservice1234.MyTCservice1234HttpSoap1" +
            "1Endpoint/")]
        public string IAM_WebReferenceNewTC_MyTCservice1234 {
            get {
                return ((string)(this["IAM_WebReferenceNewTC_MyTCservice1234"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.124.88.155:8080/axis2/services/Shactcservice.ShactcserviceHttpSoap11End" +
            "point/")]
        public string IAM_WebReferenceTCNew_Shactcservice {
            get {
                return ((string)(this["IAM_WebReferenceTCNew_Shactcservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.91.234.28:8006/sap/bc/srt/rfc/sap/ziam_read_sap_user_infomation/800/zia" +
            "m_read_sap_user_infomation/ziam_read_sap_user_infomation")]
        public string IAM_WebReferenceSapUserInfo_ZIAM_READ_SAP_USER_INFOMATIONService {
            get {
                return ((string)(this["IAM_WebReferenceSapUserInfo_ZIAM_READ_SAP_USER_INFOMATIONService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.91.234.28:8006/sap/bc/srt/rfc/sap/ziam_get_sap_user_list/600/ziam_get_s" +
            "ap_user_list/ziam_get_sap_user_list")]
        public string IAM_WebReferenceSapUserListNew_service {
            get {
                return ((string)(this["IAM_WebReferenceSapUserListNew_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.124.90.60:8002/MessageWebService.asmx")]
        public string IAM_IAMSendMailServices_MessageWebService {
            get {
                return ((string)(this["IAM_IAMSendMailServices_MessageWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hzgs211dc.hzgs.shac.com.cn/adservice/ADService.asmx")]
        public string IAM_WebReference3_Service1 {
            get {
                return ((string)(this["IAM_WebReference3_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.91.234.29:8006/sap/bc/srt/rfc/sap/ziam_get_roles_list/600/ziam_get_role" +
            "s_list/ziam_get_roles_list")]
        public string IAM_WebReferenceSapRoleNew_service {
            get {
                return ((string)(this["IAM_WebReferenceSapRoleNew_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.91.234.29:8006/sap/bc/srt/rfc/sap/ziam_get_sap_user_list/600/ziam_get_s" +
            "ap_user_list/ziam_get_sap_user_list")]
        public string IAM_WebReferenceSapUserListNew1_service {
            get {
                return ((string)(this["IAM_WebReferenceSapUserListNew1_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.91.234.29:8006/sap/bc/srt/rfc/sap/ziam_read_sap_user_infomation/600/zia" +
            "m_read_sap_user_infomation/ziam_read_sap_user_infomation")]
        public string IAM_WebReferenceSapUserInfoNew_service {
            get {
                return ((string)(this["IAM_WebReferenceSapUserInfoNew_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.124.88.176:8383/hecprod/modules/sys/WS/unit/cux_unit_ws_query.svc")]
        public string IAM2_WebReference_HEC_bumen_auto_service {
            get {
                return ((string)(this["IAM2_WebReference_HEC_bumen_auto_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.124.88.176:8383/hecprod/modules/sys/WS/position/cux_position_ws_query.s" +
            "vc")]
        public string IAM2_WebReference_HEC_Gangwei_auto_service {
            get {
                return ((string)(this["IAM2_WebReference_HEC_Gangwei_auto_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.124.88.176:8383/hecprod/modules/sys/WS/position/cux_employee_position_w" +
            "s_query.svc")]
        public string IAM2_WebReference_HEC_UserGangwei_auto_service {
            get {
                return ((string)(this["IAM2_WebReference_HEC_UserGangwei_auto_service"]));
            }
        }
    }
}
