//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18449 版自动生成。
// 
#pragma warning disable 1591

namespace IAM.WebReferenceNewTC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MyTCservice1234Soap11Binding", Namespace="http://CTree")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Exception))]
    public partial class MyTCservice1234 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback swOperationCompleted;
        
        private System.Threading.SendOrPostCallback mainaOperationCompleted;
        
        private System.Threading.SendOrPostCallback loadOperationCompleted;
        
        private System.Threading.SendOrPostCallback showinfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MyTCservice1234() {
            this.Url = global::IAM.Properties.Settings.Default.IAM_WebReferenceNewTC_MyTCservice1234;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event swCompletedEventHandler swCompleted;
        
        /// <remarks/>
        public event mainaCompletedEventHandler mainaCompleted;
        
        /// <remarks/>
        public event loadCompletedEventHandler loadCompleted;
        
        /// <remarks/>
        public event showinfoCompletedEventHandler showinfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sw", RequestNamespace="http://CTree", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sw([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Tree2 gy, [System.Xml.Serialization.XmlElementAttribute("ww", IsNullable=true)] Tree[] ww) {
            this.Invoke("sw", new object[] {
                        gy,
                        ww});
        }
        
        /// <remarks/>
        public void swAsync(Tree2 gy, Tree[] ww) {
            this.swAsync(gy, ww, null);
        }
        
        /// <remarks/>
        public void swAsync(Tree2 gy, Tree[] ww, object userState) {
            if ((this.swOperationCompleted == null)) {
                this.swOperationCompleted = new System.Threading.SendOrPostCallback(this.OnswOperationCompleted);
            }
            this.InvokeAsync("sw", new object[] {
                        gy,
                        ww}, this.swOperationCompleted, userState);
        }
        
        private void OnswOperationCompleted(object arg) {
            if ((this.swCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.swCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:maina", RequestNamespace="http://CTree", ResponseNamespace="http://CTree", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Tree2 maina() {
            object[] results = this.Invoke("maina", new object[0]);
            return ((Tree2)(results[0]));
        }
        
        /// <remarks/>
        public void mainaAsync() {
            this.mainaAsync(null);
        }
        
        /// <remarks/>
        public void mainaAsync(object userState) {
            if ((this.mainaOperationCompleted == null)) {
                this.mainaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmainaOperationCompleted);
            }
            this.InvokeAsync("maina", new object[0], this.mainaOperationCompleted, userState);
        }
        
        private void OnmainaOperationCompleted(object arg) {
            if ((this.mainaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mainaCompleted(this, new mainaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:load", RequestNamespace="http://CTree", ResponseNamespace="http://CTree", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Tree2 load() {
            object[] results = this.Invoke("load", new object[0]);
            return ((Tree2)(results[0]));
        }
        
        /// <remarks/>
        public void loadAsync() {
            this.loadAsync(null);
        }
        
        /// <remarks/>
        public void loadAsync(object userState) {
            if ((this.loadOperationCompleted == null)) {
                this.loadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloadOperationCompleted);
            }
            this.InvokeAsync("load", new object[0], this.loadOperationCompleted, userState);
        }
        
        private void OnloadOperationCompleted(object arg) {
            if ((this.loadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loadCompleted(this, new loadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:showinfo", RequestNamespace="http://CTree", ResponseNamespace="http://CTree", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public UserInfo[] showinfo() {
            object[] results = this.Invoke("showinfo", new object[0]);
            return ((UserInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void showinfoAsync() {
            this.showinfoAsync(null);
        }
        
        /// <remarks/>
        public void showinfoAsync(object userState) {
            if ((this.showinfoOperationCompleted == null)) {
                this.showinfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnshowinfoOperationCompleted);
            }
            this.InvokeAsync("showinfo", new object[0], this.showinfoOperationCompleted, userState);
        }
        
        private void OnshowinfoOperationCompleted(object arg) {
            if ((this.showinfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.showinfoCompleted(this, new showinfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CTree/xsd")]
    public partial class Tree2 {
        
        private string titleField;
        
        private Tree2[] childsField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("childs", IsNullable=true)]
        public Tree2[] childs {
            get {
                return this.childsField;
            }
            set {
                this.childsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CTree/xsd")]
    public partial class UserInfo {
        
        private string mailaddressField;
        
        private string defgroupField;
        
        private string[] groupsField;
        
        private string oSNameField;
        
        private string userNameField;
        
        private string[] groupmember_settingField;
        
        private string statusField;
        
        private string last_sync_dateField;
        
        private string userIDField;
        
        private string license_levelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mailaddress {
            get {
                return this.mailaddressField;
            }
            set {
                this.mailaddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string defgroup {
            get {
                return this.defgroupField;
            }
            set {
                this.defgroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groups", IsNullable=true)]
        public string[] groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OSName {
            get {
                return this.oSNameField;
            }
            set {
                this.oSNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groupmember_setting", IsNullable=true)]
        public string[] groupmember_setting {
            get {
                return this.groupmember_settingField;
            }
            set {
                this.groupmember_settingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string last_sync_date {
            get {
                return this.last_sync_dateField;
            }
            set {
                this.last_sync_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string license_level {
            get {
                return this.license_levelField;
            }
            set {
                this.license_levelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CTree")]
    public partial class Exception {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CTree/xsd")]
    public partial class Tree {
        
        private string typeField;
        
        private object childsField;
        
        private string titleField;
        
        private Tree parentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object childs {
            get {
                return this.childsField;
            }
            set {
                this.childsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Tree parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void swCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void mainaCompletedEventHandler(object sender, mainaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mainaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mainaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tree2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tree2)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void loadCompletedEventHandler(object sender, loadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tree2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tree2)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void showinfoCompletedEventHandler(object sender, showinfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class showinfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal showinfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserInfo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591