//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18408 版自动生成。
// 
#pragma warning disable 1591

namespace IAM.WebReferenceSapUserList {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“Policy”。
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZIAM_GET_SAP_USER_LIST_SOAP12", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZIAM_GET_SAP_USER_LISTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZiamGetSapUserListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZIAM_GET_SAP_USER_LISTService() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::IAM.Properties.Settings.Default.IAM_WebReferenceSapUserList_ZIAM_GET_SAP_USER_LISTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZiamGetSapUserListCompletedEventHandler ZiamGetSapUserListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZiamGetSapUserListResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZiamGetSapUserListResponse ZiamGetSapUserList([System.Xml.Serialization.XmlElementAttribute("ZiamGetSapUserList", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZiamGetSapUserList ZiamGetSapUserList1) {
            object[] results = this.Invoke("ZiamGetSapUserList", new object[] {
                        ZiamGetSapUserList1});
            return ((ZiamGetSapUserListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZiamGetSapUserListAsync(ZiamGetSapUserList ZiamGetSapUserList1) {
            this.ZiamGetSapUserListAsync(ZiamGetSapUserList1, null);
        }
        
        /// <remarks/>
        public void ZiamGetSapUserListAsync(ZiamGetSapUserList ZiamGetSapUserList1, object userState) {
            if ((this.ZiamGetSapUserListOperationCompleted == null)) {
                this.ZiamGetSapUserListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZiamGetSapUserListOperationCompleted);
            }
            this.InvokeAsync("ZiamGetSapUserList", new object[] {
                        ZiamGetSapUserList1}, this.ZiamGetSapUserListOperationCompleted, userState);
        }
        
        private void OnZiamGetSapUserListOperationCompleted(object arg) {
            if ((this.ZiamGetSapUserListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZiamGetSapUserListCompleted(this, new ZiamGetSapUserListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZiamGetSapUserList {
        
        private int maxRowsField;
        
        private bool maxRowsFieldSpecified;
        
        private string withUsernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public int MaxRows {
            get {
                return this.maxRowsField;
            }
            set {
                this.maxRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxRowsSpecified {
            get {
                return this.maxRowsFieldSpecified;
            }
            set {
                this.maxRowsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string WithUsername {
            get {
                return this.withUsernameField;
            }
            set {
                this.withUsernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiusname {
        
        private string usernameField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string fullnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiret2 {
        
        private string typeField;
        
        private string idField;
        
        private string numberField;
        
        private string messageField;
        
        private string logNoField;
        
        private string logMsgNoField;
        
        private string messageV1Field;
        
        private string messageV2Field;
        
        private string messageV3Field;
        
        private string messageV4Field;
        
        private string parameterField;
        
        private int rowField;
        
        private string fieldField;
        
        private string systemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string LogNo {
            get {
                return this.logNoField;
            }
            set {
                this.logNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string LogMsgNo {
            get {
                return this.logMsgNoField;
            }
            set {
                this.logMsgNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string MessageV1 {
            get {
                return this.messageV1Field;
            }
            set {
                this.messageV1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string MessageV2 {
            get {
                return this.messageV2Field;
            }
            set {
                this.messageV2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string MessageV3 {
            get {
                return this.messageV3Field;
            }
            set {
                this.messageV3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string MessageV4 {
            get {
                return this.messageV4Field;
            }
            set {
                this.messageV4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public int Row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public string System {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZiamGetSapUserListResponse {
        
        private Bapiret2[] returnField;
        
        private int rowsField;
        
        private Bapiusname[] userlistField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=(System.Xml.Schema.XmlSchemaForm)2, IsNullable=false)]
        public Bapiret2[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        public int Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=(System.Xml.Schema.XmlSchemaForm)2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=(System.Xml.Schema.XmlSchemaForm)2, IsNullable=false)]
        public Bapiusname[] Userlist {
            get {
                return this.userlistField;
            }
            set {
                this.userlistField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ZiamGetSapUserListCompletedEventHandler(object sender, ZiamGetSapUserListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZiamGetSapUserListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZiamGetSapUserListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZiamGetSapUserListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZiamGetSapUserListResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591